//testing request fro backend at 127.0.0.1
GET http://127.0.0.1:8888 

###

GET http://127.0.0.1:8888/6

###
POST http://127.0.0.1:8888 

{
  "name": "tt",
  "time": 4
}

###
DELETE http://127.0.0.1:8888/3

###
PUT http://127.0.0.1:8888/6

{
  "name": 54,
  "time": "60"
}

###
GET http://127.0.0.1:8888/bonuses

###
GET http://127.0.0.1:8888/bonuses/9


###
POST http://127.0.0.1:8888/bonuses

{
  "date": "2024-05-30",
  "bonus_ref": 6,
  "sold": 20
}

###
DELETE http://127.0.0.1:8888/bonuses/9

###
PUT http://127.0.0.1:8888/bonuses/9

{
  "date": "2024-05-26",
  "bonus_ref": 7,
  "sold": 60
}